### ISSUE TITLE
`make install` no longer working

### ISSUE THREAD

**Issue by darth-cheney** [APrioriInvestments/object_database#51]
When I try to run `make install` on the latest `dev` branch (clean directory etc), I get the following:
 
```
echo "NOTICE: File Auto-generated by Makefile" > .env
echo "export COVERAGE_PROCESS_START=/home/ecgade/projects/braxton/11-18.2/object_database/tox.ini" >> .env
echo "export PYTHONPATH=/home/ecgade/projects/braxton/11-18.2/object_database" >> .env
virtualenv .venv --python=/usr/local/bin/python3
Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local'
New python executable in /home/ecgade/projects/braxton/11-18.2/object_database/.venv/bin/python3
Also creating executable in /home/ecgade/projects/braxton/11-18.2/object_database/.venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
openssl req -x509 -newkey rsa:2048 -keyout testcert.key -nodes \
        -out testcert.cert -sha256 -days 1000 \
        -subj '/C=US/ST=New York/L=New York/CN=localhost'
Generating a RSA private key
................................................+++++
................................................+++++
writing new private key to 'testcert.key'
-----
. .venv/bin/activate; \
        pip install pipenv==2018.11.26; \
        pip install black==19.3b0; \
        pipenv install --dev --deploy; \
        pip install -e .; \
        nodeenv --python-virtualenv --prebuilt --node=10.15.3 .nodeenv; \
        npm install --global webpack webpack-cli; \
        cd object_database/web/content; \
        npm install; \
        webpack
Collecting pipenv==2018.11.26
  Using cached https://files.pythonhosted.org/packages/13/b4/3ffa55f77161cff9a5220f162670f7c5eb00df52e00939e203f601b0f579/pipenv-2018.11.26-py3-none-any.whl
Requirement already satisfied: pip>=9.0.1 in ./.venv/lib/python3.6/site-packages (from pipenv==2018.11.26) (19.3.1)
Collecting virtualenv-clone>=0.2.5
  Using cached https://files.pythonhosted.org/packages/ba/f8/50c2b7dbc99e05fce5e5b9d9a31f37c988c99acd4e8dedd720b7b8d4011d/virtualenv_clone-0.5.3-py2.py3-none-any.whl
Collecting certifi
  Using cached https://files.pythonhosted.org/packages/18/b0/8146a4f8dd402f60744fa380bc73ca47303cccf8b9190fd16a827281eac2/certifi-2019.9.11-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=36.2.1 in ./.venv/lib/python3.6/site-packages (from pipenv==2018.11.26) (41.6.0)
Collecting virtualenv
  Using cached https://files.pythonhosted.org/packages/c5/97/00dd42a0fc41e9016b23f07ec7f657f636cb672fad9cf72b80f8f65c6a46/virtualenv-16.7.7-py2.py3-none-any.whl
Installing collected packages: virtualenv-clone, certifi, virtualenv, pipenv
Successfully installed certifi-2019.9.11 pipenv-2018.11.26 virtualenv-16.7.7 virtualenv-clone-0.5.3
Collecting black==19.3b0
  Using cached https://files.pythonhosted.org/packages/30/62/cf549544a5fe990bbaeca21e9c419501b2de7a701ab0afb377bc81676600/black-19.3b0-py36-none-any.whl
Collecting attrs>=18.1.0
  Using cached https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting appdirs
  Using cached https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting click>=6.5
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting toml>=0.9.4
  Using cached https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl
Installing collected packages: attrs, appdirs, click, toml, black
Successfully installed appdirs-1.4.3 attrs-19.3.0 black-19.3b0 click-7.0 toml-0.10.0
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Installing dependencies from Pipfile.lock (0b0be3)…
Traceback (most recent call last):
  File "/home/ecgade/projects/braxton/11-18.2/object_database/.venv/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/home/ecgade/projects/braxton/11-18.2/object_database/.venv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ecgade/projects/braxton/11-18.2/object_database/.venv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ecgade/projects/braxton/11-18.2/object_database/.venv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ecgade/projects/braxton/11-18.2/object_database/.venv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ecgade/projects/braxton/11-18.2/object_database/.venv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ecgade/projects/braxton/11-18.2/object_database/.venv/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/ecgade/projects/braxton/11-18.2/object_database/.venv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ecgade/projects/braxton/11-18.2/object_database/.venv/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ecgade/projects/braxton/11-18.2/object_database/.venv/lib/python3.6/site-packages/pipenv/cli/command.py", line 254, in install
    editable_packages=state.installstate.editables,
  File "/home/ecgade/projects/braxton/11-18.2/object_database/.venv/lib/python3.6/site-packages/pipenv/core.py", line 1874, in do_install
    keep_outdated=keep_outdated
  File "/home/ecgade/projects/braxton/11-18.2/object_database/.venv/lib/python3.6/site-packages/pipenv/core.py", line 1253, in do_init
    pypi_mirror=pypi_mirror,
  File "/home/ecgade/projects/braxton/11-18.2/object_database/.venv/lib/python3.6/site-packages/pipenv/core.py", line 809, in do_install_dependencies
    deps_list = list(lockfile.get_requirements(dev=dev, only=requirements))
  File "/home/ecgade/projects/braxton/11-18.2/object_database/.venv/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/lockfile.py", line 272, in get_requirements
    yield Requirement.from_pipfile(k, v)
  File "/home/ecgade/projects/braxton/11-18.2/object_database/.venv/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 1185, in from_pipfile
    r = FileRequirement.from_pipfile(name, pipfile)
  File "/home/ecgade/projects/braxton/11-18.2/object_database/.venv/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 594, in from_pipfile
    return cls.create(**arg_dict)
  File "/home/ecgade/projects/braxton/11-18.2/object_database/.venv/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 497, in create
    cls_inst = cls(**creation_kwargs)
  File "<attrs generated init 748f2aef779e8c9fe8a150f78b48fc637115e05c>", line 35, in __init__
  File "/home/ecgade/projects/braxton/11-18.2/object_database/.venv/lib/python3.6/site-packages/pipenv/vendor/attr/validators.py", line 106, in __call__
    self.validator(inst, attr, value)
  File "/home/ecgade/projects/braxton/11-18.2/object_database/.venv/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/utils.py", line 182, in validate_path
    raise ValueError("Invalid path {0!r}".format(value))
ValueError: Invalid path './../typed_python'
```

**Comment by darth-cheney** [comment]
Looks like new pattern is to manually require the `typed_python` repository in the same parent directory of to this repository. Then the command works as expected.
